import Foundation

/// 자동 생성 문제로는 안 나오는 "그래서 무엇을 고를 것인가"를 묻는 시나리오 문항.
/// 지문은 본문 항목의 WHEN/WHY 기준을 그대로 근거로 삼는다.
enum CuratedQuestions {

    private static func q(
        _ id: String,
        _ prompt: String,
        subject: String? = nil,
        _ options: [String],
        answer: Int,
        why: String,
        source: String,
        title: String,
        lab: LabID? = nil
    ) -> Question {
        Question(
            id: "cur-\(id)",
            kind: .scenario,
            prompt: prompt,
            subject: subject,
            options: options,
            answerIndex: answer,
            explanation: why,
            sourceIndex: source,
            sourceTitle: title,
            lab: lab
        )
    }

    static let all: [Question] = [

        // MARK: 1장 — Toolbar

        q("toolbar-single",
          "이 화면의 툴바를 어떻게 구성할까요?",
          subject: "메모 편집 화면입니다. 이 화면에서 사용자가 할 수 있는 의미 있는 액션은 **완료** 하나뿐입니다.",
          ["오른쪽 상단(trailing)에 완료 버튼 하나",
           "하단 바를 만들고 그 안에 완료 버튼",
           "완료 + 공유 + 별표를 trailing 클러스터로",
           "화면 위에 뜨는 커스텀 플로팅 버튼"],
          answer: 0,
          why: "액션이 하나면 형태도 하나입니다. trailing은 iOS에서 primary action의 관례적 위치라 사용자가 학습 없이 찾습니다.\n\n하단 바는 **자주·반복해서 누르는** 액션용이라, 화면당 한 번 누르는 완료를 위해 하단 전체를 상시 점유하면 Content-First 위반입니다.",
          source: "1.1.1", title: "Single Trailing Item", lab: .toolbar),

        q("toolbar-compose",
          "메일 앱의 받은 편지함에서 **새 메일 작성** 버튼은 어디에 둘까요?",
          ["하단 바(bottom)",
           "오른쪽 상단(trailing)",
           "제목 자리(principal)",
           "왼쪽 상단(leading)"],
          answer: 0,
          why: "배치 높이는 **빈도**가 결정합니다. 메일함에서 가장 자주 반복되는 액션이므로 엄지의 홈 그라운드인 하단이 정답 — 실제 iOS 메일 앱의 배치입니다.\n\n반대로 화면당 한 번 누르는 확정성 액션(완료·저장)은 상단 trailing입니다. 빈도와 높이는 반비례해야 합니다.",
          source: "8.1.2", title: "Reachability", lab: .toolbar),

        q("toolbar-principal",
          "principal(제목 자리)에 두기에 적절한 것은?",
          ["“지도 / 목록” 세그먼트 컨트롤",
           "공유 버튼",
           "설정 버튼",
           "새 항목 추가(+) 버튼"],
          answer: 0,
          why: "principal은 **화면의 정체성**을 말하는 자리입니다. 세그먼트 값에 따라 화면 전체 내용이 바뀌므로 “이 화면이 무엇인지”와 정확히 일치합니다.\n\n공유·설정·추가는 부가 액션이라 위계상 가장 강한 중앙 자리를 쓰면 제목까지 사라지면서 화면 정체성을 말할 장치가 없어집니다.",
          source: "1.1.5", title: "Single Principal Item", lab: .toolbar),

        q("toolbar-cluster",
          "한 유리 캡슐(클러스터)에 묶어도 되는 조합은?",
          ["실행취소 · 재실행",
           "정렬 · 삭제",
           "공유 · 설정 · 삭제 · 정렬",
           "완료 · 취소 · 새로고침"],
          answer: 0,
          why: "Liquid Glass에서 **묶음 자체가 의미**입니다 — 같은 캡슐에 있으면 사용자는 “한 세트”로 읽습니다.\n\n실행취소/재실행은 같은 축의 짝이라 한 세트가 참이지만, 정렬(도구)과 삭제(파괴적 액션)를 묶으면 묶음이 거짓 정보가 되어 인지 부담만 커집니다.",
          source: "1.1.3", title: "Leading and Trailing Clusters", lab: .toolbar),

        q("toolbar-leading",
          "push로 들어온 상세 화면입니다. leading에 도구 클러스터를 두려고 합니다.",
          subject: "뒤로가기 버튼이 있는 상세 화면의 왼쪽 상단에 보기 전환·정렬 버튼 묶음을 배치",
          ["뒤로가기와 자리를 다투므로 피한다",
           "leading은 도구 자리이므로 문제없다",
           "뒤로가기를 없애고 클러스터를 넣는다",
           "클러스터를 principal로 옮긴다"],
          answer: 0,
          why: "leading 클러스터는 뒤로가기 버튼 자리와 경쟁합니다. 루트 화면이나 모달처럼 **back이 없는 화면**에서 주로 쓰는 패턴입니다.\n\nleading은 “이동”의 문법이 선점한 자리라, 도구를 넣으려면 이동 장치가 없는 화면이어야 합니다.",
          source: "1.1.2", title: "Leading Cluster and Trailing Item", lab: .toolbar),

        q("toolbar-overflow",
          "툴바 아이템이 많아 공간이 모자랍니다. 시스템은 어떻게 처리하나요?",
          ["넘치는 아이템을 overflow 메뉴(⋯)로 접는다",
           "버튼들을 균등하게 축소해 모두 표시한다",
           "가장 오른쪽 아이템부터 잘라 버린다",
           "툴바를 두 줄로 늘린다"],
          answer: 0,
          why: "무한정 축소하면 손가락 크기 이하로 작아져 **“눌리는가”** 기준이 깨집니다. 그래서 시스템이 자동으로 접어 최소 터치 타깃을 보장합니다.\n\n기능의 완전성은 유지하면서 화면 점유는 사용 빈도에 비례시키는 처리입니다.",
          source: "1.1.7", title: "Trailing Overflowing Cluster", lab: .toolbar),

        q("title-large",
          "Large 타이틀이 스크롤하면 inline으로 접히는 이유는?",
          ["진입 시점엔 방향감이 필요하지만 읽기 시작하면 기여가 끝나므로",
           "큰 제목이 성능에 부담을 주므로",
           "inline이 시각적으로 더 아름다우므로",
           "제목 길이가 길어질 수 있으므로"],
          answer: 0,
          why: "**“이 UI 요소가 지금 이 순간 과업에 기여하는가?”** — Large 타이틀은 진입 순간 “여기가 어디인지”를 알려주며 기여하지만, 읽기 시작하면 기여가 끝납니다.\n\n그 순간 공간을 콘텐츠에 반납하는 것이 Content-First. 기여 여부를 순간마다 다시 묻는 동작입니다.",
          source: "8.1.1", title: "Content-First · Minimization", lab: .toolbar),

        q("title-menu",
          "현재 폴더 이름이 제목으로 보이는 화면에서 “이름 변경 / 폴더 전환”을 어디에 둘까요?",
          ["제목을 탭하면 열리는 toolbarTitleMenu",
           "제목 옆의 별도 “폴더 변경” 버튼",
           "trailing의 ⋯ 메뉴",
           "하단 바의 전용 버튼"],
          answer: 0,
          why: "액션의 **대상이 화면에 보인다면 대상을 직접 조작**하게 합니다. 폴더 이름이 제목으로 보이므로 그 제목을 탭하는 것이 자연스럽습니다.\n\n별도 버튼을 만들면 사용자가 “이 버튼이 저 제목에 대한 것”임을 유추해야 하고, 툴바 자리도 하나 더 씁니다.",
          source: "1.2.5", title: "Inline with Toolbar Title Menu", lab: .toolbar),

        q("title-menu-scope",
          "toolbarTitleMenu에 넣으면 안 되는 항목은?",
          ["로그아웃 · 앱 설정",
           "이 폴더 이름 변경",
           "이 폴더 삭제",
           "다른 폴더로 전환"],
          answer: 0,
          why: "제목 메뉴는 **“제목이 가리키는 대상”에 대한 액션** 자리입니다.\n\n무관한 전역 액션을 넣으면 대상–액션 결합이라는 문법 자체가 거짓이 되어, 이후 이 앱의 모든 title menu를 사용자가 못 믿게 됩니다.",
          source: "8.1.7", title: "직접 조작", lab: .toolbar),

        // MARK: 1.3 / 6장 — Scroll Edge Effect · Materials

        q("edge-photo",
          "사진 위에 툴바가 떠 있는 화면에서 버튼 대비가 부족합니다. 어떻게 할까요?",
          ["hard scroll edge effect + 두꺼운 material 배경",
           "scroll edge effect를 hidden으로 끈다",
           "버튼에 불투명 배경색을 직접 지정한다",
           "버튼 색을 더 밝은 흰색으로 바꾼다"],
          answer: 0,
          why: "투명함은 미학이고 컨트롤이 읽히는 건 기능입니다. 충돌하면 **가독성이 이깁니다** — 투명도를 포기하고 불투명 배경으로 대비를 확보하는 것이 공식 탈출구입니다.\n\n유리 위에 임의 배경색을 얹으면 시스템의 재질 계층이 깨져 다크모드·투명도 감소 설정에서 대비가 예측 불가능해집니다.",
          source: "1.3.3", title: "Hard with Thick Material Toolbar Background", lab: .scrollEdge),

        q("edge-verify",
          "scroll edge effect를 hidden으로 끄기 전에 반드시 확인해야 하는 것은?",
          ["가장 밝은/복잡한 콘텐츠가 바 뒤를 지날 때 컨트롤이 읽히는지",
           "다크 모드에서 잘 보이는지",
           "애니메이션이 부드러운지",
           "스크롤 성능이 떨어지지 않는지"],
          answer: 0,
          why: "검증 기준은 **가장 좋은 조건이 아니라 가장 나쁜 조건**입니다. 밝은 화면 하나만 보고 끄면, 흰 사진이 바 뒤를 지나는 순간 컨트롤이 사라집니다.\n\n접근성 설정(큰 글씨·투명도 감소)까지 포함해서 최악의 조합을 확인해야 합니다.",
          source: "8.1.4", title: "가독성 > 미학", lab: .scrollEdge),

        q("material-thickness",
          "material 두께를 고르는 기준은?",
          ["뒤로 지나갈 콘텐츠가 복잡할수록 두껍게",
           "화면이 클수록 두껍게",
           "다크 모드일수록 두껍게",
           "레이어가 위에 있을수록 얇게"],
          answer: 0,
          why: "material은 뒤를 비춤으로써 “이 레이어는 콘텐츠 위에 떠 있다”는 깊이 관계를 표현합니다. 뒤가 복잡할수록 비침이 가독성을 해치므로 두께로 보정합니다.\n\n1.3.3의 가독성 논리와 완전히 같은 기준입니다.",
          source: "6.1.1", title: "Materials in Different Backgrounds", lab: .scrollEdge),

        // MARK: 2장 — Text

        q("text-money",
          "리스트 셀에 금액 **₩1,234,000**을 넣는데 폭이 모자랍니다.",
          subject: "어떤 처리가 기준에 맞나요?",
          ["minimumScaleFactor로 글자를 줄인다",
           "기본 .tail truncation으로 자른다",
           ".middle truncation으로 가운데를 접는다",
           "lineLimit(2)로 두 줄로 흘린다"],
          answer: 0,
          why: "기준은 **“잘려도 뜻이 통하는가?”** 입니다. 금액은 잘리는 순간 정보가 파괴되는 “값”이라 자르면 안 되고 줄여야 합니다.\n\n“₩1,234,0…”은 뜻이 통하는 게 아니라 **틀린 값**을 보여주는 것입니다. 타이머(12:34:56)도 같습니다.",
          source: "2.1.3", title: "Scale to Fit", lab: .text),

        q("text-path",
          "파일 경로 `/Users/leeo/Documents/…/report.pdf` 를 한 줄에 표시할 때 truncation은?",
          [".middle — 가운데를 접는다",
           ".tail — 뒤를 자른다",
           ".head — 앞을 자른다",
           "자르지 않고 scale로 줄인다"],
          answer: 0,
          why: "경로는 앞이 공통 접두사(`/Users/이름/`)라 앞만 보이면 항목을 구분할 수 없습니다. 정보 가치가 **양 끝**에 있으니 가운데를 접는 것이 기준에 맞습니다.",
          source: "2.1.2", title: "Truncation", lab: .text),

        q("text-scale-limit",
          "minimumScaleFactor를 0.3까지 내려야 텍스트가 들어갑니다.",
          subject: "이 상황을 어떻게 봐야 할까요?",
          ["축소가 아니라 설계 문제 — 폭을 늘리거나 표기를 줄인다",
           "0.3도 시스템이 허용하므로 문제없다",
           "폰트를 더 좁은 것으로 바꾼다",
           "lineLimit을 늘려 여러 줄로 흘린다"],
          answer: 0,
          why: "잘림·축소는 **안전장치이지 레이아웃 설계 수단이 아닙니다.** 절반 이하로 줄여야 들어간다면 레이아웃이 틀린 것입니다.\n\n폭을 늘리거나 표기 자체를 줄이는 것(1,234,000 → 1.2M)이 정답입니다.",
          source: "8.1.5", title: "공간은 계약, 텍스트는 가변", lab: .text),

        q("text-reserve",
          "`lineLimit(2, reservesSpace: true)` 가 적절한 곳은?",
          ["가로 스크롤 카드처럼 높이가 균일해야 하는 그리드",
           "세로로 긴 설정 목록",
           "본문 상세 화면",
           "한 줄짜리 제목 레이블"],
          answer: 0,
          why: "공간 예약의 목적은 **그리드·가로 카드의 균일성**입니다. 짧은 텍스트에도 두 줄 높이를 확보해 카드 높이가 들쭉날쭉해지는 걸 막습니다.\n\n균일성이 필요 없는 세로 목록에 걸면 짧은 셀마다 빈 공간만 상시 소모합니다.",
          source: "2.1.4", title: "Line Limit (Range · Reserve Space)", lab: .text),

        q("format-unit",
          "거리 값을 화면에 표시하려 합니다. 미국 사용자에게는 마일로 보여야 합니다.",
          ["Measurement 값만 갖고 .measurement 포맷에 맡긴다",
           "`\"\\(distance) km\"` 로 조립하고 미국이면 변환한다",
           "로케일을 읽어 if 문으로 단위를 분기한다",
           "설정 화면에서 사용자가 단위를 고르게 한다"],
          answer: 0,
          why: "앱은 **값만 소유하고 표기는 시스템에 위임**합니다. 같은 Measurement가 한국에선 “5킬로미터”, 미국에선 “3.1 miles”로 자동 렌더링됩니다.\n\n문자열로 조립하는 순간 표기 규칙이 코드에 굳어 국제화 버그가 심어집니다.",
          source: "2.2.1", title: "Format Styles (Units)", lab: .text),

        q("format-name",
          "사용자 이름을 표시할 때 `\"\\(firstName) \\(lastName)\"` 의 문제는?",
          ["이름 순서는 데이터가 아니라 문화권 규칙이라 “길동 홍”이 된다",
           "문자열 보간이 성능에 불리하다",
           "옵셔널 처리가 안 되어 크래시가 난다",
           "공백이 두 번 들어갈 수 있다"],
          answer: 0,
          why: "이름 순서·이니셜 추출 규칙은 문화권마다 다릅니다. PersonNameComponents로 값만 갖고 표기는 시스템에 맡겨야 합니다.\n\n**“데이터를 문자열로 직접 조립하는가? 그 표기 규칙이 문화권마다 다른가?”** 둘 다 예스면 이미 버그입니다.",
          source: "2.2.2", title: "Name Formatting", lab: .text),

        // MARK: 3장 — Tab Bar

        q("tab-count",
          "최상위 영역이 7개인 앱입니다. iPhone 탭바를 어떻게 할까요?",
          ["3~5개로 추리고 나머지는 탭 안의 화면으로 내린다",
           "7개를 모두 탭으로 넣는다",
           "탭바를 두 줄로 만든다",
           "탭바를 없애고 전부 메뉴로 넣는다"],
          answer: 0,
          why: "5개를 넘으면 각 타깃이 엄지 정확도 아래로 좁아지고, 최상위 개념이 많아지면 구조 자체가 안 읽힙니다.\n\n**“모든 걸 탭으로”가 아니라 덜 중요한 건 탭 안의 화면으로** 내리는 것이 원칙입니다.",
          source: "3.2.3", title: "4 Tabs", lab: .tabBar),

        q("tab-search-role",
          "iOS 26에서 검색 탭을 둘 때의 표준은?",
          ["`Tab(role: .search)` 로 역할만 선언한다",
           "마지막 탭에 돋보기 아이콘을 직접 넣는다",
           "탭바 대신 상단 searchable을 쓴다",
           "검색 버튼을 bottom accessory에 넣는다"],
          answer: 0,
          why: "탭은 “장소 이동”이지만 검색은 **“모드 진입”** 입니다. 성격이 다르므로 시스템이 별도 캡슐로 분리해 OS 전역에서 일관되게 표현합니다.\n\n역할만 선언하면 위치·모양·전환 동작을 시스템이 처리하고, 탭하면 캡슐이 그 자리에서 검색 필드로 변형됩니다.",
          source: "3.4.2", title: "With Search Role", lab: .tabBar),

        q("tab-badge",
          "배지를 붙일 탭을 고르는 기준은?",
          ["“몇 개인지”가 들어갈지 말지를 결정할 때",
           "그 탭이 가장 중요한 탭일 때",
           "새 콘텐츠가 있는 모든 탭",
           "사용자가 오래 안 들어간 탭"],
          answer: 0,
          why: "배지는 사용자를 부르는 **인터럽트 장치**입니다. 숫자를 보고 들어갈지 판단하는 종류의 정보일 때만 값을 합니다.\n\n모든 탭에 배지를 달면 인터럽트 가치가 인플레이션되어 진짜 중요한 알림이 묻힙니다.",
          source: "3.1.3", title: "Badge Count", lab: .tabBar),

        q("tab-accessory",
          "음악 재생 미니 플레이어처럼 어느 탭에 있든 유지돼야 하는 UI는?",
          ["tabViewBottomAccessory — 탭바 계층에 붙인다",
           "각 탭의 화면 하단에 각각 구현한다",
           "safeAreaBar(edge: .bottom)로 만든다",
           "nonmodal 시트로 띄운다"],
          answer: 0,
          why: "탭을 넘나드는 상태는 특정 화면이 아니라 **앱 전역의 소유**라, 탭 콘텐츠가 아닌 탭바 계층에 붙입니다.\n\n탭바가 접힐 때 액세서리가 사라지지 않고 탭바 자리로 승격되는 처리까지 시스템이 해줍니다.",
          source: "3.5.1", title: "Bottom Accessory", lab: .tabBar),

        q("tab-hide",
          "탭바를 상세 화면에서 숨기는 것이 맞는 경우는?",
          ["사진 전체 화면·영상 재생처럼 몰입이 주 작업일 때",
           "상세 화면이 스크롤이 길 때",
           "상세 화면에 툴바가 있을 때",
           "탭이 5개를 넘을 때"],
          answer: 0,
          why: "목록에선 이동이 주 작업이지만 상세에선 소비가 주 작업입니다 — **주 작업이 바뀌면 크롬도 바뀌는** 것이 content-first.\n\n다만 얕은 계층이라면 탭바는 “지금 어디에 있는지”를 보여주는 상시 지도이므로 유지가 기본값입니다.",
          source: "3.3.2", title: "Hidden on Detail Views", lab: .tabBar),

        // MARK: 4장 — Sheets

        q("sheet-medium",
          "지도 위에 검색 결과 목록을 띄웁니다. 어떤 detent가 맞나요?",
          [".medium — 배경 지도를 보면서 결과를 본다",
           ".large — 결과에 집중시킨다",
           "fullScreenCover",
           "custom(120pt)"],
          answer: 0,
          why: "절반 높이는 **“원본과의 대화”** 은유입니다 — 화면을 나눠 가짐으로써 시트가 배경 콘텐츠에 대한 것임을 형태로 말합니다.\n\n훑어보기와 집중이 둘 다 필요하면 `[.medium, .large]` 콤보로 높이 선택권을 사용자에게 넘기는 것이 더 좋습니다.",
          source: "4.1.2", title: "Presentation Detent: Medium", lab: .sheet),

        q("sheet-nonmodal",
          "지도를 계속 움직이면서 결과 시트를 유지해야 합니다.",
          ["presentationBackgroundInteraction으로 모달성을 제거한다",
           "시트를 닫았다 다시 여는 흐름으로 만든다",
           "시트 대신 화면 하단에 커스텀 뷰를 얹는다",
           ".large detent로 올려 지도를 가린다"],
          answer: 0,
          why: "모달의 본질은 “응답을 요구하고 나머지를 차단”인데, 도구 패널은 응답이 아니라 **병행 작업**입니다.\n\n시트의 형태(하단 패널)만 빌리고 모달성은 제거한 것이 nonmodal 시트입니다. 딤이 없는 것이 “뒤를 만져도 된다”는 시각 신호입니다.",
          source: "4.1.5", title: "Nonmodal Sheet", lab: .sheet),

        q("sheet-zoom",
          "카드를 탭하면 그 카드의 상세 시트가 열립니다. 전환은?",
          ["zoom — 탭한 카드에서 확대되어 열린다",
           "standard — 아래에서 올라온다",
           "fade",
           "push 전환"],
          answer: 0,
          why: "눌렀던 것과 열린 것이 **같은 것임을 모션으로 증명**하는 장치입니다. 공간적 연속성이 유지되어 “어디서 왔는지”를 설명할 필요가 없습니다.\n\nstandard는 출처 정보를 버리므로, 출처가 의미 있을 때는 zoom이 정답입니다.",
          source: "4.3.2", title: "Zoom – Sheet", lab: .sheet),

        q("sheet-cover",
          "온보딩·로그인 흐름에 fullScreenCover를 쓰는 이유는?",
          ["실수로 쓸어내려 이탈하면 흐름이 깨지므로",
           "시트보다 애니메이션이 빠르므로",
           "배경을 렌더링하지 않아 성능이 좋으므로",
           "detent를 지정할 필요가 없으므로"],
          answer: 0,
          why: "뒤가 전혀 안 보이고 제스처 닫기도 없는 **“끝내거나, 명시적으로 나가라”**는 강한 모달성입니다.\n\n가벼운 시트와 무거운 커버를 시스템이 굳이 별도 API로 나눈 건, 이 무게 차이가 곧 사용자 기대의 문제이기 때문입니다.",
          source: "4.2.1", title: "Full Screen Cover", lab: .sheet),

        // MARK: 5장 — Safe Area Bar

        q("safearea-why",
          "커스텀 하단 컨트롤 바를 만들 때 safeAreaBar를 쓰는 이유는?",
          ["인셋 + 스크롤 가장자리 효과를 시스템이 대주므로",
           "overlay보다 렌더링이 빠르므로",
           "자동으로 탭바처럼 보이므로",
           "다크 모드 색을 알아서 맞춰주므로"],
          answer: 0,
          why: "overlay는 콘텐츠를 **가리고**, safeAreaInset은 밀어내기만 하고 가장자리 효과가 없습니다.\n\nsafeAreaBar는 **시스템 바의 인프라 전체를 커스텀 뷰에 개방**한 것 — 커스텀 UI도 시스템 바와 같은 문법으로 읽히고, 홈 인디케이터 분기도 사라집니다.",
          source: "5.1.3", title: "Bottom Safe Area Bar"),

        q("safearea-consistency",
          "위에는 필터 바, 아래에는 컨트롤 바가 함께 있는 화면입니다.",
          subject: "위는 soft, 아래는 hard 가장자리 효과를 쓰려고 합니다.",
          ["둘을 같은 효과로 통일해야 재질 은유가 유지된다",
           "위아래 역할이 다르므로 달라도 된다",
           "아래는 항상 hard가 맞다",
           "가장자리 효과는 시스템 바에만 적용된다"],
          answer: 0,
          why: "위아래가 같은 효과로 통일되어야 콘텐츠가 **“두 유리 사이를 지나는 하나의 면”**으로 읽힙니다.\n\n위는 soft인데 아래만 hard면 한 화면 안에서 재질 은유가 깨집니다.",
          source: "5.1.5", title: "Top & Bottom, Soft Scroll Edge Effect"),

        // MARK: 7장 — Menu

        q("menu-order",
          "메뉴 안에서 파괴적 액션(삭제)은 어떻게 배치하나요?",
          ["Divider로 분리하고 빨간색으로",
           "맨 위에 눈에 띄게",
           "다른 항목과 같은 그룹 안에",
           "아이콘 없이 텍스트만"],
          answer: 0,
          why: "메뉴의 가치는 배치 규약이 **시스템 전역에서 동일해 학습이 필요 없다**는 것입니다.\n\n자주 쓰는 항목은 버튼 가까운 쪽에, 관련 항목은 섹션으로 묶고, 파괴적 액션은 Divider로 분리해 빨간색 — 이 규약을 지켜야 사용자가 실수로 누르지 않습니다.",
          source: "7.1.1", title: "Menu Configurations", lab: .toolbar),

        q("menu-vs-toolbar",
          "메뉴(⋯)로 접어야 할 액션과 툴바에 노출할 액션을 가르는 기준은?",
          ["지금 이 화면의 과업에 기여할 확률(사용 빈도)",
           "액션 이름의 길이",
           "구현 난이도",
           "액션이 파괴적인지 여부"],
          answer: 0,
          why: "드물게 쓰는 액션은 지금의 과업에 기여할 확률이 낮으므로 접어둡니다 — 기능의 완전성은 유지하면서 **화면 점유는 기여도에 비례**시키는 것입니다.\n\n툴바 overflow가 자동으로 만드는 것도 결국 이 메뉴입니다.",
          source: "8.1.1", title: "Content-First · Minimization", lab: .toolbar),
    ]
}
